# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualizer.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1123, 916)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Dialog.setFont(font)
        Dialog.setAutoFillBackground(False)
        self.lineEdit_VMAddr0 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr0.setGeometry(QtCore.QRect(332, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr0.setFont(font)
        self.lineEdit_VMAddr0.setText("")
        self.lineEdit_VMAddr0.setCursorPosition(0)
        self.lineEdit_VMAddr0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr0.setReadOnly(True)
        self.lineEdit_VMAddr0.setPlaceholderText("")
        self.lineEdit_VMAddr0.setObjectName("lineEdit_VMAddr0")
        self.lineEdit_VMAddr1 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr1.setGeometry(QtCore.QRect(332, 250, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr1.setFont(font)
        self.lineEdit_VMAddr1.setCursorPosition(0)
        self.lineEdit_VMAddr1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr1.setReadOnly(True)
        self.lineEdit_VMAddr1.setPlaceholderText("")
        self.lineEdit_VMAddr1.setObjectName("lineEdit_VMAddr1")
        self.lineEdit_VMAddr2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr2.setGeometry(QtCore.QRect(332, 290, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr2.setFont(font)
        self.lineEdit_VMAddr2.setCursorPosition(0)
        self.lineEdit_VMAddr2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr2.setReadOnly(True)
        self.lineEdit_VMAddr2.setPlaceholderText("")
        self.lineEdit_VMAddr2.setObjectName("lineEdit_VMAddr2")
        self.lineEdit_VMAddr3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr3.setGeometry(QtCore.QRect(332, 330, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr3.setFont(font)
        self.lineEdit_VMAddr3.setCursorPosition(0)
        self.lineEdit_VMAddr3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr3.setReadOnly(True)
        self.lineEdit_VMAddr3.setPlaceholderText("")
        self.lineEdit_VMAddr3.setObjectName("lineEdit_VMAddr3")
        self.lineEdit_VMAddr4 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr4.setGeometry(QtCore.QRect(332, 370, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr4.setFont(font)
        self.lineEdit_VMAddr4.setCursorPosition(0)
        self.lineEdit_VMAddr4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr4.setReadOnly(True)
        self.lineEdit_VMAddr4.setPlaceholderText("")
        self.lineEdit_VMAddr4.setObjectName("lineEdit_VMAddr4")
        self.lineEdit_VMAddr5 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr5.setGeometry(QtCore.QRect(332, 410, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr5.setFont(font)
        self.lineEdit_VMAddr5.setCursorPosition(0)
        self.lineEdit_VMAddr5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr5.setReadOnly(True)
        self.lineEdit_VMAddr5.setPlaceholderText("")
        self.lineEdit_VMAddr5.setObjectName("lineEdit_VMAddr5")
        self.lineEdit_VMAddr6 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr6.setGeometry(QtCore.QRect(332, 450, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr6.setFont(font)
        self.lineEdit_VMAddr6.setCursorPosition(0)
        self.lineEdit_VMAddr6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr6.setReadOnly(True)
        self.lineEdit_VMAddr6.setPlaceholderText("")
        self.lineEdit_VMAddr6.setObjectName("lineEdit_VMAddr6")
        self.lineEdit_VMAddr7 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr7.setGeometry(QtCore.QRect(332, 490, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr7.setFont(font)
        self.lineEdit_VMAddr7.setCursorPosition(0)
        self.lineEdit_VMAddr7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr7.setReadOnly(True)
        self.lineEdit_VMAddr7.setPlaceholderText("")
        self.lineEdit_VMAddr7.setObjectName("lineEdit_VMAddr7")
        self.lineEdit_VMAddr8 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr8.setGeometry(QtCore.QRect(332, 530, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr8.setFont(font)
        self.lineEdit_VMAddr8.setCursorPosition(0)
        self.lineEdit_VMAddr8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr8.setReadOnly(True)
        self.lineEdit_VMAddr8.setPlaceholderText("")
        self.lineEdit_VMAddr8.setObjectName("lineEdit_VMAddr8")
        self.lineEdit_VMAddr9 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr9.setGeometry(QtCore.QRect(332, 570, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr9.setFont(font)
        self.lineEdit_VMAddr9.setCursorPosition(0)
        self.lineEdit_VMAddr9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr9.setReadOnly(True)
        self.lineEdit_VMAddr9.setPlaceholderText("")
        self.lineEdit_VMAddr9.setObjectName("lineEdit_VMAddr9")
        self.lineEdit_VMAddr10 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr10.setGeometry(QtCore.QRect(332, 610, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr10.setFont(font)
        self.lineEdit_VMAddr10.setCursorPosition(0)
        self.lineEdit_VMAddr10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr10.setReadOnly(True)
        self.lineEdit_VMAddr10.setPlaceholderText("")
        self.lineEdit_VMAddr10.setObjectName("lineEdit_VMAddr10")
        self.lineEdit_VMAddr11 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr11.setGeometry(QtCore.QRect(332, 650, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr11.setFont(font)
        self.lineEdit_VMAddr11.setCursorPosition(0)
        self.lineEdit_VMAddr11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr11.setReadOnly(True)
        self.lineEdit_VMAddr11.setPlaceholderText("")
        self.lineEdit_VMAddr11.setObjectName("lineEdit_VMAddr11")
        self.lineEdit_VMAddr12 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr12.setGeometry(QtCore.QRect(332, 690, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr12.setFont(font)
        self.lineEdit_VMAddr12.setCursorPosition(0)
        self.lineEdit_VMAddr12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr12.setReadOnly(True)
        self.lineEdit_VMAddr12.setPlaceholderText("")
        self.lineEdit_VMAddr12.setObjectName("lineEdit_VMAddr12")
        self.lineEdit_VMAddr13 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr13.setGeometry(QtCore.QRect(332, 730, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr13.setFont(font)
        self.lineEdit_VMAddr13.setCursorPosition(0)
        self.lineEdit_VMAddr13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr13.setReadOnly(True)
        self.lineEdit_VMAddr13.setPlaceholderText("")
        self.lineEdit_VMAddr13.setObjectName("lineEdit_VMAddr13")
        self.lineEdit_VMAddr14 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr14.setGeometry(QtCore.QRect(332, 770, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr14.setFont(font)
        self.lineEdit_VMAddr14.setCursorPosition(0)
        self.lineEdit_VMAddr14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr14.setReadOnly(True)
        self.lineEdit_VMAddr14.setPlaceholderText("")
        self.lineEdit_VMAddr14.setObjectName("lineEdit_VMAddr14")
        self.lineEdit_VMAddr15 = QtGui.QLineEdit(Dialog)
        self.lineEdit_VMAddr15.setGeometry(QtCore.QRect(332, 810, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_VMAddr15.setFont(font)
        self.lineEdit_VMAddr15.setCursorPosition(0)
        self.lineEdit_VMAddr15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_VMAddr15.setReadOnly(True)
        self.lineEdit_VMAddr15.setPlaceholderText("")
        self.lineEdit_VMAddr15.setObjectName("lineEdit_VMAddr15")
        self.lineEdit_PABit1 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit1.setGeometry(QtCore.QRect(450, 250, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit1.setFont(font)
        self.lineEdit_PABit1.setCursorPosition(0)
        self.lineEdit_PABit1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit1.setReadOnly(True)
        self.lineEdit_PABit1.setPlaceholderText("")
        self.lineEdit_PABit1.setObjectName("lineEdit_PABit1")
        self.lineEdit_PABit2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit2.setGeometry(QtCore.QRect(450, 290, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit2.setFont(font)
        self.lineEdit_PABit2.setCursorPosition(0)
        self.lineEdit_PABit2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit2.setReadOnly(True)
        self.lineEdit_PABit2.setPlaceholderText("")
        self.lineEdit_PABit2.setObjectName("lineEdit_PABit2")
        self.lineEdit_PABit3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit3.setGeometry(QtCore.QRect(450, 330, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit3.setFont(font)
        self.lineEdit_PABit3.setCursorPosition(0)
        self.lineEdit_PABit3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit3.setReadOnly(True)
        self.lineEdit_PABit3.setPlaceholderText("")
        self.lineEdit_PABit3.setObjectName("lineEdit_PABit3")
        self.label_1 = QtGui.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(140, 210, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_1.setFont(font)
        self.label_1.setMouseTracking(False)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 250, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(140, 290, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(140, 330, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(140, 370, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(140, 410, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(140, 450, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(140, 490, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(140, 530, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(140, 570, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(140, 610, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(140, 650, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(140, 690, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(140, 730, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(140, 770, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(140, 810, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(800, 450, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(800, 490, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(800, 530, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(800, 570, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.lineEdit_PABit4 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit4.setGeometry(QtCore.QRect(450, 370, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit4.setFont(font)
        self.lineEdit_PABit4.setCursorPosition(0)
        self.lineEdit_PABit4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit4.setReadOnly(True)
        self.lineEdit_PABit4.setPlaceholderText("")
        self.lineEdit_PABit4.setObjectName("lineEdit_PABit4")
        self.lineEdit_PABit5 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit5.setGeometry(QtCore.QRect(450, 410, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit5.setFont(font)
        self.lineEdit_PABit5.setCursorPosition(0)
        self.lineEdit_PABit5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit5.setReadOnly(True)
        self.lineEdit_PABit5.setPlaceholderText("")
        self.lineEdit_PABit5.setObjectName("lineEdit_PABit5")
        self.lineEdit_PABit6 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit6.setGeometry(QtCore.QRect(450, 450, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit6.setFont(font)
        self.lineEdit_PABit6.setCursorPosition(0)
        self.lineEdit_PABit6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit6.setReadOnly(True)
        self.lineEdit_PABit6.setPlaceholderText("")
        self.lineEdit_PABit6.setObjectName("lineEdit_PABit6")
        self.lineEdit_PABit7 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit7.setGeometry(QtCore.QRect(450, 490, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit7.setFont(font)
        self.lineEdit_PABit7.setCursorPosition(0)
        self.lineEdit_PABit7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit7.setReadOnly(True)
        self.lineEdit_PABit7.setPlaceholderText("")
        self.lineEdit_PABit7.setObjectName("lineEdit_PABit7")
        self.lineEdit_PABit8 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit8.setGeometry(QtCore.QRect(450, 530, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit8.setFont(font)
        self.lineEdit_PABit8.setCursorPosition(0)
        self.lineEdit_PABit8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit8.setReadOnly(True)
        self.lineEdit_PABit8.setPlaceholderText("")
        self.lineEdit_PABit8.setObjectName("lineEdit_PABit8")
        self.lineEdit_PABit9 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit9.setGeometry(QtCore.QRect(450, 570, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit9.setFont(font)
        self.lineEdit_PABit9.setCursorPosition(0)
        self.lineEdit_PABit9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit9.setReadOnly(True)
        self.lineEdit_PABit9.setPlaceholderText("")
        self.lineEdit_PABit9.setObjectName("lineEdit_PABit9")
        self.lineEdit_PABit10 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit10.setGeometry(QtCore.QRect(450, 610, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit10.setFont(font)
        self.lineEdit_PABit10.setCursorPosition(0)
        self.lineEdit_PABit10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit10.setReadOnly(True)
        self.lineEdit_PABit10.setPlaceholderText("")
        self.lineEdit_PABit10.setObjectName("lineEdit_PABit10")
        self.lineEdit_PABit11 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit11.setGeometry(QtCore.QRect(450, 650, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit11.setFont(font)
        self.lineEdit_PABit11.setCursorPosition(0)
        self.lineEdit_PABit11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit11.setReadOnly(True)
        self.lineEdit_PABit11.setPlaceholderText("")
        self.lineEdit_PABit11.setObjectName("lineEdit_PABit11")
        self.lineEdit_PABit12 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit12.setGeometry(QtCore.QRect(450, 690, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit12.setFont(font)
        self.lineEdit_PABit12.setCursorPosition(0)
        self.lineEdit_PABit12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit12.setReadOnly(True)
        self.lineEdit_PABit12.setPlaceholderText("")
        self.lineEdit_PABit12.setObjectName("lineEdit_PABit12")
        self.lineEdit_PABit13 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit13.setGeometry(QtCore.QRect(450, 730, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit13.setFont(font)
        self.lineEdit_PABit13.setCursorPosition(0)
        self.lineEdit_PABit13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit13.setReadOnly(True)
        self.lineEdit_PABit13.setPlaceholderText("")
        self.lineEdit_PABit13.setObjectName("lineEdit_PABit13")
        self.lineEdit_PABit14 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit14.setGeometry(QtCore.QRect(450, 770, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit14.setFont(font)
        self.lineEdit_PABit14.setCursorPosition(0)
        self.lineEdit_PABit14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit14.setReadOnly(True)
        self.lineEdit_PABit14.setPlaceholderText("")
        self.lineEdit_PABit14.setObjectName("lineEdit_PABit14")
        self.lineEdit_PABit15 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit15.setGeometry(QtCore.QRect(450, 810, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit15.setFont(font)
        self.lineEdit_PABit15.setCursorPosition(0)
        self.lineEdit_PABit15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit15.setReadOnly(True)
        self.lineEdit_PABit15.setPlaceholderText("")
        self.lineEdit_PABit15.setObjectName("lineEdit_PABit15")
        self.lineEdit_PMAddr1 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PMAddr1.setGeometry(QtCore.QRect(692, 490, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PMAddr1.setFont(font)
        self.lineEdit_PMAddr1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PMAddr1.setReadOnly(True)
        self.lineEdit_PMAddr1.setPlaceholderText("")
        self.lineEdit_PMAddr1.setObjectName("lineEdit_PMAddr1")
        self.lineEdit_PMAddr2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PMAddr2.setGeometry(QtCore.QRect(692, 530, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PMAddr2.setFont(font)
        self.lineEdit_PMAddr2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PMAddr2.setReadOnly(True)
        self.lineEdit_PMAddr2.setPlaceholderText("")
        self.lineEdit_PMAddr2.setObjectName("lineEdit_PMAddr2")
        self.lineEdit_PMAddr3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PMAddr3.setGeometry(QtCore.QRect(692, 570, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PMAddr3.setFont(font)
        self.lineEdit_PMAddr3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PMAddr3.setReadOnly(True)
        self.lineEdit_PMAddr3.setPlaceholderText("")
        self.lineEdit_PMAddr3.setObjectName("lineEdit_PMAddr3")
        self.label_21 = QtGui.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(140, 100, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(800, 340, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(170, 180, 321, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_23 = QtGui.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(450, 150, 40, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(680, 420, 291, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_24 = QtGui.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(690, 390, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(300, 100, 20, 751))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(810, 340, 20, 271))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_25 = QtGui.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(680, 740, 401, 131))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.pushButton_Connect = QtGui.QPushButton(Dialog)
        self.pushButton_Connect.setGeometry(QtCore.QRect(670, 40, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Connect.setFont(font)
        self.pushButton_Connect.setAutoFillBackground(False)
        self.pushButton_Connect.setCheckable(False)
        self.pushButton_Connect.setObjectName("pushButton_Connect")
        self.pushButton_Disconnect = QtGui.QPushButton(Dialog)
        self.pushButton_Disconnect.setGeometry(QtCore.QRect(890, 40, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        self.pushButton_Disconnect.setFont(font)
        self.pushButton_Disconnect.setObjectName("pushButton_Disconnect")
        self.lineEdit_PMAddr0 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PMAddr0.setGeometry(QtCore.QRect(692, 450, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PMAddr0.setFont(font)
        self.lineEdit_PMAddr0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PMAddr0.setReadOnly(True)
        self.lineEdit_PMAddr0.setPlaceholderText("")
        self.lineEdit_PMAddr0.setObjectName("lineEdit_PMAddr0")
        self.lineEdit_PABit0 = QtGui.QLineEdit(Dialog)
        self.lineEdit_PABit0.setGeometry(QtCore.QRect(450, 210, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PABit0.setFont(font)
        self.lineEdit_PABit0.setCursorPosition(0)
        self.lineEdit_PABit0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PABit0.setReadOnly(True)
        self.lineEdit_PABit0.setPlaceholderText("")
        self.lineEdit_PABit0.setObjectName("lineEdit_PABit0")
        self.lineEdit_VMAddr0.raise_()
        self.lineEdit_VMAddr1.raise_()
        self.lineEdit_VMAddr2.raise_()
        self.lineEdit_VMAddr3.raise_()
        self.lineEdit_VMAddr4.raise_()
        self.lineEdit_VMAddr5.raise_()
        self.lineEdit_VMAddr6.raise_()
        self.lineEdit_VMAddr7.raise_()
        self.lineEdit_VMAddr8.raise_()
        self.lineEdit_VMAddr9.raise_()
        self.lineEdit_VMAddr10.raise_()
        self.lineEdit_VMAddr11.raise_()
        self.lineEdit_VMAddr12.raise_()
        self.lineEdit_VMAddr13.raise_()
        self.lineEdit_VMAddr14.raise_()
        self.lineEdit_VMAddr15.raise_()
        self.lineEdit_PABit1.raise_()
        self.lineEdit_PABit2.raise_()
        self.lineEdit_PABit3.raise_()
        self.lineEdit_PABit0.raise_()
        self.label_1.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.lineEdit_PABit4.raise_()
        self.lineEdit_PABit5.raise_()
        self.lineEdit_PABit6.raise_()
        self.lineEdit_PABit7.raise_()
        self.lineEdit_PABit8.raise_()
        self.lineEdit_PABit9.raise_()
        self.lineEdit_PABit10.raise_()
        self.lineEdit_PABit11.raise_()
        self.lineEdit_PABit12.raise_()
        self.lineEdit_PABit13.raise_()
        self.lineEdit_PABit14.raise_()
        self.lineEdit_PABit15.raise_()
        self.lineEdit_PMAddr1.raise_()
        self.lineEdit_PMAddr2.raise_()
        self.lineEdit_PMAddr3.raise_()
        self.lineEdit_PMAddr0.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.line.raise_()
        self.label_23.raise_()
        self.line_2.raise_()
        self.label_24.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.label_25.raise_()
        self.pushButton_Connect.raise_()
        self.pushButton_Disconnect.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ECE562"))
        self.label_1.setText(_translate("Dialog", "0B - 1B"))
        self.label_2.setText(_translate("Dialog", "2B - 3B"))
        self.label_3.setText(_translate("Dialog", "4B - 5B"))
        self.label_4.setText(_translate("Dialog", "6B - 7B"))
        self.label_5.setText(_translate("Dialog", "8B - 9B"))
        self.label_6.setText(_translate("Dialog", "10B - 11B"))
        self.label_7.setText(_translate("Dialog", "12B - 13B"))
        self.label_8.setText(_translate("Dialog", "14B - 15B"))
        self.label_9.setText(_translate("Dialog", "16B - 17B"))
        self.label_10.setText(_translate("Dialog", "18B - 19B"))
        self.label_11.setText(_translate("Dialog", "20B - 21B"))
        self.label_12.setText(_translate("Dialog", "22B - 23B"))
        self.label_13.setText(_translate("Dialog", "24B - 25B"))
        self.label_14.setText(_translate("Dialog", "26B - 27B"))
        self.label_15.setText(_translate("Dialog", "28B - 29B"))
        self.label_16.setText(_translate("Dialog", "30B - 31B"))
        self.label_17.setText(_translate("Dialog", "0B - 1B"))
        self.label_18.setText(_translate("Dialog", "2B - 3B"))
        self.label_19.setText(_translate("Dialog", "4B - 5B"))
        self.label_20.setText(_translate("Dialog", "6B - 7B"))
        self.label_21.setText(_translate("Dialog", "Virtual Address Space"))
        self.label_22.setText(_translate("Dialog", "Physical Memory Address"))
        self.label_23.setText(_translate("Dialog", "V"))
        self.label_24.setText(_translate("Dialog", "Page"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:18pt;\">V</span> .......... Valid (1) or Not-Valid (0)</p><p align=\"justify\">B ...................... 1 Byte = 8 bits</p></body></html>"))
        self.pushButton_Connect.setText(_translate("Dialog", "Connect"))
        self.pushButton_Disconnect.setText(_translate("Dialog", "Disconnect"))

